### ISSUE TITLE
Occurs When Filtering VSOURCE

### ISSUE THREAD

**Issue by estasney** [estasney/FlaskAPI#122]
Exception on /stage [POST]#012Traceback (most recent call last):#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise#012    raise value#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view#012    return func(*args, **kwargs)#012  File "/home/estasney1/mysite/app_folder/files/routes.py", line 251, in stage_file#012    file_response = stage_file_filter(preview=preview)#012  File "/home/estasney1/mysite/app_folder/files/routes.py", line 231, in stage_file_filter#012    sheet_stream = matched_facade.filter_transform(request, as_df=preview)#012  File "/home/estasney1/mysite/app_folder/facades.py", line 760, in filter_transform#012    filtered_records = self.filter_records(request_obj)#012  File "/home/estasney1/mysite/app_folder/facades.py", line 708, in filter_records#012    base_query = file_obj.profiles.join(LinkedInRecord.contacts).filter(*contact_criteria)#012  File "<string>", line 2, in filter#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 201, in generate#012    fn(self, *args[1:], **kw)#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1597, in filter#012    criterion = expression._expression_literal_as_text(criterion)#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 4254, in _expression_literal_as_text#012    return _literal_as_text(element, warn=True)#012  File "/home/estasney1/.virtualenvs/hermes/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 4275, in _literal_as_text#012    "instead" % type(element)#012sqlalchemy.exc.ArgumentError: SQL expression object or string expected, got object of type <class 'function'> instead

**Comment by estasney** [comment]
Class was not consolidated

https://github.com/estasney/FlaskAPI/blob/63311fdfe2040be3d057f4c4a675238756c8e430/mysite/app_folder/facades.py#L645-L719
